import pyautogui
import time
pyautogui.FAILSAFE = False
import esc_button
import os

def funcao_alterar_ip_colibri():
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('alt', '1')
    time.sleep(0.5)
    pyautogui.hotkey('alt', '1')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("root", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("vi /etc/systemd/network/wired.network", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('i')
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("    [Match]", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("    Name=eth0", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite(" ", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("    [Network]", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("    Address=192.168.2.15/24", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("    Gateway=192.168.2.254", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("    DNS=8.8.8.8", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('esc')
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite(":wq!", interval=0.02)
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(2)

    esc_button.checar_botao_emergencia()

    pyautogui.typewrite("systemctl stop systemd-networkd.socket", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("systemctl stop systemd-networkd.service", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("cd /", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("mkdir opt", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("reboot", interval=0.02)
    print("ANtes do enter")
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    print("DEpois do Enter")
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()

    #! SSH ROOT
    import ssh_root
    ssh_root.funcao_ssh_root()
    esc_button.checar_botao_emergencia()