import pyautogui
import time
pyautogui.FAILSAFE = False
import pickle
import esc_button
import os

def funcao_move_files():

    try:
        with open("versao_escolhida.pkl", "rb") as f:
            versao_escolhida = pickle.load(f)
    except FileNotFoundError:
        print("Arquivo de versão não encontrado.")
        return
    except Exception as e:
        print(f"Erro ao ler o arquivo de versão: {e}")
        return

    time.sleep(2)
    import abrir_nova_aba_terminal
    abrir_nova_aba_terminal.funcao_abrir_nova_aba_terminal()
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    # pyautogui.typewrite("cd Documents/V2.0.0", interval=0.02)
    pyautogui.typewrite(f"cd Documents/{versao_escolhida}", interval=0.02)
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    pyautogui.typewrite("chmod +x ./movefiles.sh", interval=0.02)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite('./movefiles.sh', interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    time.sleep(3)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("192.168.2.15", interval=0.02)
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(0.5)
    pyautogui.typewrite("s", interval=0.02)
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()

    # Voltar para a primeira aba, aba do sudo minicom.
    pyautogui.hotkey('alt', '1')
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("root")
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("cd /opt", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("chmod +x ./init.sh", 0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("./init.sh", interval= 0.02)
    pyautogui.hotkey('enter')
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    time.sleep(1)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("reboot", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    # Voltar para o terminal do movefiles.sh, passar pasta agtech_app.
    pyautogui.hotkey('alt', '5')
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(5)
    pyautogui.typewrite("scp agtech_app root@192.168.2.15:/opt/agtech_app/bin/", interval=0.02)
    time.sleep(1)
    pyautogui.hotkey('enter')
    time.sleep(5)
    import check_agtech_app
    check_agtech_app.encontrar_agtech_app()
    time.sleep(1)
    esc_button.checar_botao_emergencia()

    # Voltar para o primeiro terminal (do sudo minicom) e verificar se agtech_app foi passada corretamente.
    time.sleep(2)
    pyautogui.hotkey('alt', '1')
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("root")
    pyautogui.hotkey('enter')
    esc_button.checar_botao_emergencia()
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("cd /opt/agtech_app/bin", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("ls", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(2)
    esc_button.checar_botao_emergencia()
    # Concedendo permissões para agtech_app.
    pyautogui.typewrite("cd /", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("cd /", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("chmod +x /opt/agtech_app/bin/agtech_app", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("chmod +x /opt/*", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()
    pyautogui.typewrite("chmod +x /usr/bin/can-bringup.sh", interval=0.02)
    pyautogui.hotkey('enter')
    time.sleep(0.5)
    esc_button.checar_botao_emergencia()

    if versao_escolhida == "V2.2.0":
        print("Você selecionou a versão V2.2.O.")
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite("reboot", interval=0.02)
        time.sleep(1)
        pyautogui.hotkey('enter')
        esc_button.checar_botao_emergencia()
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        pyautogui.press("enter")
        esc_button.checar_botao_emergencia()
        time.sleep(5)
        pyautogui.typewrite("setenv vidargs 'video=mxcfb0:dev=lcd,TDO07,if=RGB666 video=mxcfb1:off fbmem8'", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(0.5)
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite("saveenv", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(3)
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite("reset", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(3)
        esc_button.checar_botao_emergencia()
        import abrir_nova_aba_terminal
        abrir_nova_aba_terminal.funcao_abrir_nova_aba_terminal()
        time.sleep(2)
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite(f"cd Documents/V2.2.0/eject-hboard-0.3", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(5)
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite("scp zImage root@192.168.2.15:/media/mmcblk0p1 ", interval=0.05)
        time.sleep(2)
        pyautogui.hotkey('enter')
        time.sleep(1)
        import check_zImage
        check_zImage.encontrar_zImage()
        time.sleep(3)
        esc_button.checar_botao_emergencia()
        time.sleep(1)
        esc_button.checar_botao_emergencia()
        time.sleep(1)
        esc_button.checar_botao_emergencia()
        time.sleep(1)
        time.sleep(3)
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite("scp imx6dl-colibri-eval-v3.dtb root@192.168.2.15:/media/mmcblk0p1", interval=0.05)
        time.sleep(2)
        pyautogui.hotkey('enter')
        time.sleep(1)
        import check_imxd6l
        check_imxd6l.encontrar_imx6dl()
        time.sleep(1)
        esc_button.checar_botao_emergencia()
        time.sleep(3)
        esc_button.checar_botao_emergencia()
        time.sleep(1)
        esc_button.checar_botao_emergencia()
        time.sleep(1)
        esc_button.checar_botao_emergencia()
        time.sleep(1)
        pyautogui.hotkey('alt', '1')
        esc_button.checar_botao_emergencia()
        time.sleep(2)
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite("root", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(2)
        esc_button.checar_botao_emergencia()
        pyautogui.typewrite("poweroff", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(7)
        esc_button.checar_botao_emergencia()
        print(f"Fim de gravação {versao_escolhida}")
        import gravacao_concluida
        gravacao_concluida.funcao_gravacao_concluida()      
        time.sleep(0.5)
        os._exit(0)

    else:
        print("Versão selecionada não é V2.2.O.")
        pyautogui.typewrite("reboot", interval=0.02)
        pyautogui.hotkey('enter')

        # Finalizando o processo.
        time.sleep(15)
        pyautogui.typewrite("root", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(2)
        pyautogui.typewrite("poweroff", interval=0.02)
        pyautogui.hotkey('enter')
        time.sleep(7)

        import gravacao_concluida
        gravacao_concluida.funcao_gravacao_concluida()
        print(f"Fim de gravação {versao_escolhida}")
        time.sleep(0.5)
        os._exit(0)
    
